language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-werx' ]; then cd .. && eval "mv $currentfolder generator-werx" && cd generator-werx; fi
